### ISSUE TITLE
Add Signin Screen with react-navigator setup

### ISSUE THREAD

**Issue by marcos8896** [marcos8896/nutrition-care-react-native#2]

**Comment by brandonvilla21** [comment]
Shouldn't this issue be renamed to "Sign Up" 🤔

**Comment by marcos8896** [comment]
@brandonvilla21 
From what I understand, I think it is right to use "Log in" in this case 🤔.
[Source](https://ell.stackexchange.com/questions/24384/what-is-the-difference-among-sign-up-sign-in-and-log-in)

**Comment by brandonvilla21** [comment]
Ok. There is already a Signing screen which does what is specified in this issue. Should we close this and rename it to Login instead?

**Comment by marcos8896** [comment]
@brandonvilla21 
Yep 😄

**Comment by brandonvilla21** [comment]
Anuma, that's true. Let's leave it that way then 👍
